[workspace]
resolver = "2"
members = [ 
    "client",
    "quic-session",
    "server",
    "client",
    "eframe_template",
    "framework",
]

[patch.crates-io]
egui = { git = "https://github.com/emilk/egui.git", rev = "f4ed394" }
eframe = { git = "https://github.com/emilk/egui.git", rev = "f4ed394" }
